name: lint # Имя workflow для отображения в UI GitHub

on: # Отрабатывает при триггерах:
  push:
    branches: [main] # Если убрать условие branches, то отработает на push в любую ветку
  pull_request:
    branches: [main] # В квадратных скобках можно указать несколько веток

# Workflow состоит из одной или нескольких job, работающих параллельно по умолчанию
jobs: # Описываем job-ы
  eslint: # Название job-ы, на которое можно ссылаться (например, в другой job-e: needs: eslint)
    runs-on: ubuntu-latest # Описываем окружение (имя docker-образа, на котором будет запускаться)
    steps: # Шаги (переменные окружения не сохраняются между шагами и их нужно пробрасывать, если требуется)
      - uses: actions/checkout@v2 # Используем общий github action для клонирования нашего репозитория

      # Устанавливаем NVM
      - name: Install NVM # Имя для отображения в UI GitHub
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash # Команда для установки NVM из официального README.md NVM

      # Активируем NVM и устанавливаем NodeJS
      - name: Install NodeJS
        env: # Объявление переменных окружения
          NODE_VERSION: 14.17.0 # Версия NodeJS в переменной окружения, которую NVM будет использовать
        run: export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use && nvm install $NODE_VERSION # Запуск NVM для установки NodeJS

      # Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # Lint исходного кода
      - name: Lint source code with ESLint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install NodeJS
        env:
          NODE_VERSION: 14.17.0
        run: export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use && nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm ci
      - name: Check format source code with prettier
        run: npm run check:format

  eslint-with-node-image:
    runs-on: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Check format source code with prettier
        run: npm run check:format

  prettier-with-node-image:
    runs-on: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Check format source code with prettier
        run: npm run check:format
